language: node_js

sudo: false

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install: 
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/spmeesseman)

env:
  VSCE_TOKEN: $(vsceToken)
  GH_TOKEN: $(githubToken)
  GIT_AUTHOR_EMAIL: $(gitEmail)
  GIT_COMMITTER_EMAIL: $(gitEmail)
  GIT_AUTHOR_NAME: $(gitName)
  GIT_COMMITTER_NAME: $(gitName)
